### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-intro-Vh2K33#1] opened 2017-01-29 02:48 UTC
@chrisvfritz Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-js-intro-Vh2K33/) and meets the following criteria:

- [x] At least 3 `button` elements are included in your page
- [x] When each of the buttons are hovered over (`mouseenter` event) or clicked on (`click` event), a unique sound effect plays from an `audio` element (try the `.play()` method) -- you may use [these drum kit sounds](/static/audio/drum-sounds.zip), create ones from [this sound effects generator](http://sfbgames.com/chiptone/), or use any other sounds that won't hurt/irritate the people who listen to them
- [x] Each button is well-labeled, corresponding to the sound it will play
- [x] All `audio` elements are invisible (no `controls` attribute), so that they can only be played with the buttons
- [x] All of your JavaScript is in a separate file ending with `.js`

**Comment by chrisvfritz** [comment] 2017-01-30 05:15
Wow, this is definitely above and beyond! 🚀  Some things I really like:

- Bootstrap is expertly used to customize the page layout 🍰 
- Well-organized files 🍪
- A lot of sounds - I almost feel like a real DJ! 😂  🍭

There are just a few areas for improvement:

### Indentation

The 4-space indentation you're using looks very consistent, which I'm happy to see! For these projects though, we're standardizing on 2-space indention, as noted [in a previous lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/3). That page I linked to also has some tips for quickly indenting / de-indenting lines that should be helpful. 🙂

One anomaly that I noticed however: the closing `</head>` should be on its own line, at the same indentation level as opening `<head>`. That was probably just a typo, but let's fix that as well.

### `mouseenter` vs `mouseover`

I'm excited to see that you know about even more events than we've covered in the lessons! I wouldn't recommend using `mouseover` instead of `mouseenter` though, as there's an important difference. If you check out the demo at [the bottom of this page](https://api.jquery.com/mouseover/#example-0), you'll see that while `mouseenter` fires _only_ when initially entering the element, `mouseover` will _also_ fire whenever entering or leaving a child element, which I've never actually found useful - and can actually cause unintended behavior in many cases. 

Right now, there are no other elements inside of your buttons, but you never know when you might want to add child elements. For example, you might decide to add icons that match each drum sound. Because of this, I would recommend just staying away from `mouseover`. 😄 

### JavaScript must be a separate file

I enjoyed the cleverness of your solution, using a function and passing in the `id`. 👍  However, one of the criteria for this project is to actually have _all_ JavaScript in a separate `.js` file. The main reason we added that is because the attributes for adding events (e.g. `onclick`, `onmouseenter`) actually limit you to only one callback per event. If you wanted to add _two_ (or more) separate callbacks, it would be impossible.

On the other hand, using `addEventListener` allows you to add as many callbacks to an event as you want. Though we haven't talked about this in a lesson, you can even individually _remove_ any of these with `removeEventListener`. It's very powerful!

---

Let me know if you have any questions or thoughts. I'm happy to provide more information and provide more information if you'd like. 🙂  Otherwise, let me know when the project is updated and keep up the great work!

**Comment by kisyular** [comment] 2017-01-31 21:31
@chrisvfritz, I made the suggested changes. Take a look and I will appreciate feedback

**Comment by chrisvfritz** [comment] 2017-02-01 01:19
This looks really fantastic! 🎉 🎈 🚀 :shipit: 

As a bonus, I'll also share a little trick. 🙂  This is definitely not something we expect you to be able to do yet, but you could actually shorten your code using named functions. Since the only thing that changes is the name of the sound, you can pass it in as the `soundName` argument below, then use it to attach all your sounds:

``` js
var attachSoundToButton = function (soundName) {
  var button = document.getElementById(soundName)
  var audio = new Audio('sounds/' + soundName + '.wav')
  var playSound = function () {
    audio.play()
  }
  button.addEventListener('click', playSound)
  button.addEventListener('mouseenter', playSound)
}

attachSoundToButton('boom')
attachSoundToButton('clap')
attachSoundToButton('hihat')
attachSoundToButton('kick')
attachSoundToButton('openhat')
attachSoundToButton('snare')
attachSoundToButton('tink')
attachSoundToButton('tom')
attachSoundToButton('ride')
```

If you have any questions about the code above, I'm happy to answer. 😄  Otherwise, I look forward to your next project!

**Closed as completed** 2017-02-02 04:34 UTC
